package main.java.kd.jkdl.sql.api;

import java.sql.PreparedStatement;
import java.sql.SQLException;

/**
 * An object that represents a precompiled SQL statement.
 * 
 * @author <a href="mailto:k.dobrzynski94@gmail.com">Krzysztof Dobrzyñski</a> -> https://github.com/Sejoslaw
 * @see PreparedStatement
 */
public interface ISQLPreparedStatement 
{
	/**
	 * Just in case that user may need something more.
	 * 
	 * @return Returns the {@link PreparedStatement} itself.
	 */
	@Deprecated
	PreparedStatement getStatement();
	
	/**
	 * @return Returns the Database from this statement.
	 * @see ISQLDatabase
	 */
	ISQLDatabase getDatabase();
	
	/**
	 * @return Returns Table MetaData.
	 * @see ISQLTableMetaData
	 */
	ISQLTableMetaData getTableMetaData();
	
	/**
	 * @return Returns the SQL command from which this statement was created.
	 */
	String getSQLCommand();
	
	/**
	 * @return Returns the name of the Table.
	 */
	String getTableName();
	
	/**
	 * @return An object that can be used to get information about the types 
	 * and properties for each parameter.
	 * @throws SQLException
	 * @see ISQLParameterMetaData
	 * @see {@link PreparedStatement#getParameterMetaData()}
	 */
	ISQLParameterMetaData getParameterMetaData() throws SQLException;
	
	/**
	 * @return Executes the SQL query in this SQLPreparedStatement object and returns the 
	 * SQLTable object generated by the query.
	 * @throws SQLException
	 * @see ISQLTable
	 */
	ISQLTable executeQuery() throws SQLException;
	
	/**
	 * @see PreparedStatement#executeUpdate()
	 */
	int executeUpdate() throws SQLException;
}